server:
  port: 80
spring:
  application:
    name: cloud-consumer-feign-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机版
      defaultZone: http://localhost:7001/eureka
logging:
  level:
    com.atguigu.springcloud.service.PaymentFeignService: debug